apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmgvar
  namespace: fortimanager
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmgdata
  namespace: fortimanager
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce